"""Proliz OBS kullanan universiteler (Proliz/OBS tarzi giris icin).

Kaynak: Proliz Yazilim resmi referanslar sayfasi
(https://www.prolizyazilim.com/referanslar.html) — Proliz sistemlerini
kullanan universiteler. Liste alfabetik siralidir; basta demo hesaplarin
bagli oldugu "Demo Üniversitesi" yer alir.

Bu liste tek kaynaktan (backend) servis edilir; web ve mobil istemciler
`GET /auth/universities` uzerinden ceker. Gercek OBS/Proliz API'si
baglaninca bu modul o API'ye devredilecek (istemcilerde degisiklik gerekmez).
"""

# Demo/giris hesaplari bu universiteye bagli (giris okul no + sifre ile yapilir).
DEMO_UNIVERSITY = "Demo Üniversitesi"

# Proliz referanslarindaki universiteler (alfabetik).
PROLIZ_UNIVERSITIES: list[str] = [
    "Abdullah Gül Üniversitesi",
    "Acıbadem Üniversitesi",
    "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
    "Adıyaman Üniversitesi",
    "Afyon Kocatepe Üniversitesi",
    "Ağrı İbrahim Çeçen Üniversitesi",
    "Akdeniz Üniversitesi",
    "Aksaray Üniversitesi",
    "Alanya Alaaddin Keykubat Üniversitesi",
    "Alanya Üniversitesi",
    "Amasya Üniversitesi",
    "Ankara Bilim Üniversitesi",
    "Ankara Hacı Bayram Veli Üniversitesi",
    "Ankara Müzik ve Güzel Sanatlar Üniversitesi",
    "Ankara Sosyal Bilimler Üniversitesi",
    "Ankara Yıldırım Beyazıt Üniversitesi",
    "Antalya Belek Üniversitesi",
    "Artvin Çoruh Üniversitesi",
    "ARUCAD Üniversitesi",
    "Ataşehir Adıgüzel Meslek Yüksekokulu",
    "Avrasya Üniversitesi",
    "Balıkesir Üniversitesi",
    "Batman Üniversitesi",
    "Beykent Üniversitesi",
    "Bezmiâlem Vakıf Üniversitesi",
    "Biruni Üniversitesi",
    "Bitlis Eren Üniversitesi",
    "Burdur Mehmet Akif Ersoy Üniversitesi",
    "Bursa Teknik Üniversitesi",
    "Cumhuriyet Üniversitesi",
    "Dicle Üniversitesi",
    "Doğuş Üniversitesi",
    "Dumlupınar Üniversitesi",
    "Erzincan Binali Yıldırım Üniversitesi",
    "Esenyurt Üniversitesi",
    "Fatih Sultan Mehmet Üniversitesi",
    "Fenerbahçe Üniversitesi",
    "Fırat Üniversitesi",
    "Gazi Üniversitesi",
    "Gaziantep Üniversitesi",
    "Gaziosmanpaşa Üniversitesi",
    "Gebze Teknik Üniversitesi",
    "Gedik Üniversitesi",
    "Gümüşhane Üniversitesi",
    "Hacettepe Üniversitesi",
    "Hakkari Üniversitesi",
    "Haliç Üniversitesi",
    "Harran Üniversitesi",
    "Hasan Kalyoncu Üniversitesi",
    "Hatay Mustafa Kemal Üniversitesi",
    "İbn Haldun Üniversitesi",
    "İnönü Üniversitesi",
    "İskenderun Teknik Üniversitesi",
    "İstanbul Arel Üniversitesi",
    "İstanbul Okan Üniversitesi",
    "İstanbul Ticaret Üniversitesi",
    "İzmir Demokrasi Üniversitesi",
    "İzmir Ekonomi Üniversitesi",
    "İzmir Kavram Meslek Yüksekokulu",
    "Kafkas Üniversitesi",
    "Kahramanmaraş İstiklal Üniversitesi",
    "Kahramanmaraş Sütçü İmam Üniversitesi",
    "Kapadokya Üniversitesi",
    "Karabük Üniversitesi",
    "Karamanoğlu Mehmetbey Üniversitesi",
    "Kayseri Üniversitesi",
    "Kıbrıs Sosyal Bilimler Üniversitesi",
    "Kırıkkale Üniversitesi",
    "Kırklareli Üniversitesi",
    "Kırşehir Ahi Evran Üniversitesi",
    "Kilis 7 Aralık Üniversitesi",
    "Konya Gıda ve Tarım Üniversitesi",
    "KTO Karatay Üniversitesi",
    "Kütahya Sağlık Bilimleri Üniversitesi",
    "Lefke Avrupa Üniversitesi",
    "Lokman Hekim Üniversitesi",
    "Malatya Turgut Özal Üniversitesi",
    "Manisa Celal Bayar Üniversitesi",
    "Mardin Artuklu Üniversitesi",
    "MEF Üniversitesi",
    "Mersin Üniversitesi",
    "Milli Savunma Üniversitesi",
    "Muğla Sıtkı Koçman Üniversitesi",
    "Muş Alparslan Üniversitesi",
    "Necmettin Erbakan Üniversitesi",
    "Nuh Naci Yazgan Üniversitesi",
    "Osmaniye Korkut Ata Üniversitesi",
    "OSTİM Teknik Üniversitesi",
    "Rumeli Üniversitesi",
    "Sağlık Bilimleri Üniversitesi",
    "Samsun Üniversitesi",
    "Siirt Üniversitesi",
    "Sinop Üniversitesi",
    "Süleyman Demirel Üniversitesi",
    "Şırnak Üniversitesi",
    "Tokat Gaziosmanpaşa Üniversitesi",  # TOGÜ (pilot okul; Proliz referans sayfasinda yok, elle eklendi)
    "Trakya Üniversitesi",
    "Türk Alman Üniversitesi",
    "Türk Hava Kurumu Üniversitesi",
    "Ufuk Üniversitesi",
    "Uşak Üniversitesi",
    "Üsküdar Üniversitesi",
    "Yaşar Üniversitesi",
    "Yeni Yüzyıl Üniversitesi",
    "Yıldız Teknik Üniversitesi",
    "Yüksek İhtisas Üniversitesi",
    "Zonguldak Bülent Ecevit Üniversitesi",
]

# Giris ekraninda gosterilen liste: demo ustte, ardindan gercek referanslar.
UNIVERSITIES: list[str] = [DEMO_UNIVERSITY, *PROLIZ_UNIVERSITIES]
